export { default as HeroSection } from './HeroSection'
export { default as CNCMadeEasySection } from './CNCMadeEasySection'
export { default as PopularDetailsSection } from './PopularDetailsSection'
export { default as RevolutionizingSection } from './RevolutionizingSection'
export { default as VideoSection } from './VideoSection'
